/**
 * Códigos de trazabilidad del Limit Engine.
 * Sin textos de UI — Cockpit / PDF / IA los traducen.
 */

export const LimitTraceCode = {
  VALIDATE_POLICY: "LIMIT.VALIDATE_POLICY",
  POLICY_INVALID: "LIMIT.POLICY_INVALID",
  POLICY_DISABLED: "LIMIT.POLICY_DISABLED",
  SCORE_NOT_OK: "LIMIT.SCORE_NOT_OK",
  RESOLVE_CATEGORY: "LIMIT.RESOLVE_CATEGORY",
  CATEGORY_MISSING: "LIMIT.CATEGORY_MISSING",
  RESOLVE_CONFIDENCE: "LIMIT.RESOLVE_CONFIDENCE",
  RESOLVE_COMMERCIAL_BASE: "LIMIT.RESOLVE_COMMERCIAL_BASE",
  COMMERCIAL_FACTOR_MISSING: "LIMIT.COMMERCIAL_FACTOR_MISSING",
  SALES_MISSING: "LIMIT.SALES_MISSING",
  APPLY_CATEGORY_MULTIPLIER: "LIMIT.APPLY_CATEGORY_MULTIPLIER",
  CATEGORY_BAND_MISSING: "LIMIT.CATEGORY_BAND_MISSING",
  MULTIPLIER_MISSING: "LIMIT.MULTIPLIER_MISSING",
  CATEGORY_DENY: "LIMIT.CATEGORY_DENY",
  APPLY_POLICY_RULE: "LIMIT.APPLY_POLICY_RULE",
  SKIP_POLICY_RULE: "LIMIT.SKIP_POLICY_RULE",
  APPLY_RESTRICTION_CEILING: "LIMIT.APPLY_RESTRICTION_CEILING",
  APPLY_RESTRICTION_GUARANTEES: "LIMIT.APPLY_RESTRICTION_GUARANTEES",
  APPLY_RESTRICTION_REVIEW: "LIMIT.APPLY_RESTRICTION_REVIEW",
  MANUAL_OVERRIDE_SKIPPED: "LIMIT.MANUAL_OVERRIDE_SKIPPED",
  APPLY_MANUAL_OVERRIDE: "LIMIT.APPLY_MANUAL_OVERRIDE",
  FINAL_RESULT: "LIMIT.FINAL_RESULT",
} as const

export type LimitTraceCodeValue =
  (typeof LimitTraceCode)[keyof typeof LimitTraceCode]

